"""initial schema

Revision ID: c03dec85f67a
Revises: 
Create Date: 2026-03-09 20:53:09.972416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c03dec85f67a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('party', 'person', 'org', 'location', 'system', 'other', name='entitytype'), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('notification_events',
    sa.Column('event_type', sa.Enum('processing_complete', 'deadline_approaching', 'items_awaiting_review', 'risk_detected', 'weekly_summary_ready', name='notificationeventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('oidc_provider', sa.Enum('google', 'microsoft', name='oidcprovider'), nullable=False),
    sa.Column('oidc_subject', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oidc_provider', 'oidc_subject', name='uq_user_oidc')
    )
    op.create_table('assets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='auditaction'), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_performed_at', 'audit_log', ['performed_at'], unique=False)
    op.create_index('ix_audit_table_record', 'audit_log', ['table_name', 'record_id'], unique=False)
    op.create_table('config_overrides',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_config_key')
    )
    op.create_table('prompt_versions',
    sa.Column('prompt_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Enum('contract', 'inspection_report', 'rfi', 'change_order', 'invoice', 'unknown', name='documenttype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_name', 'version', name='uq_prompt_version')
    )
    op.create_table('user_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'read', name='notificationstatus'), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['notification_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_notifications_status', 'user_notifications', ['user_id', 'status'], unique=False)
    op.create_table('documents',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('processed_file_path', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('doc_type', sa.Enum('contract', 'inspection_report', 'rfi', 'change_order', 'invoice', 'unknown', name='documenttype'), server_default='unknown', nullable=False),
    sa.Column('doc_type_confidence', sa.Float(), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('parse_status', sa.Enum('uploaded', 'parsing', 'ocr', 'chunking', 'classification', 'extraction', 'verification', 'scoring', 'complete', 'partially_processed', 'failed', name='parsestatus'), server_default='uploaded', nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('scanned_page_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('user_asset_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_user_asset')
    )
    op.create_table('chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_sha256', sa.String(), nullable=False),
    sa.Column('split_reason', sa.Enum('full_page', 'section_split', 'token_limit', name='splitreason'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_document_page', 'chunks', ['document_id', 'page_number'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), server_default='', nullable=False),
    sa.Column('normalized_text', sa.Text(), server_default='', nullable=False),
    sa.Column('text_source', sa.Enum('pdf_text', 'ocr', name='textsource'), nullable=False),
    sa.Column('text_sha256', sa.String(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('has_tables', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processed', 'failed', name='pageprocessingstatus'), server_default='pending', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_page')
    )
    op.create_table('entity_mentions',
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('mentioned_name', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('suggested_entity_id', sa.UUID(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggested_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.Enum('classification', 'entity_extraction', 'obligation_extraction', 'risk_extraction', name='extractionstage'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'superseded', name='extractionstatus'), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_runs_document_stage', 'extraction_runs', ['document_id', 'stage'], unique=False)
    op.create_table('text_spans',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('span_text', sa.Text(), nullable=False),
    sa.Column('span_sha256', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_text_spans_document_page', 'text_spans', ['document_id', 'page_number'], unique=False)
    op.create_table('obligations',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('obligation_type', sa.Enum('compliance', 'submission', 'payment', 'inspection', 'notification', 'other', name='obligationtype'), nullable=False),
    sa.Column('obligation_text', sa.Text(), nullable=False),
    sa.Column('modality', sa.Enum('must', 'shall', 'required', 'should', 'may', 'unknown', name='modality'), nullable=False),
    sa.Column('responsible_entity_id', sa.UUID(), nullable=True),
    sa.Column('due_kind', sa.Enum('absolute', 'relative', 'resolved_relative', 'none', name='duekind'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_rule', sa.Text(), nullable=True),
    sa.Column('trigger_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('needs_review', 'confirmed', 'rejected', name='reviewstatus'), server_default='needs_review', nullable=False),
    sa.Column('system_confidence', sa.Integer(), nullable=False),
    sa.Column('reviewer_confidence', sa.Integer(), nullable=True),
    sa.Column('has_external_reference', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('contradiction_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('reviewer_confidence IS NULL OR (reviewer_confidence >= 0 AND reviewer_confidence <= 100)', name='ck_obligation_rev_conf'),
    sa.CheckConstraint('system_confidence >= 0 AND system_confidence <= 100', name='ck_obligation_sys_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['responsible_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obligations_document_status', 'obligations', ['document_id', 'status'], unique=False)
    op.create_index('ix_obligations_due_date', 'obligations', ['due_date'], unique=False, postgresql_where=sa.text('due_date IS NOT NULL'))
    op.create_index('ix_obligations_status_severity', 'obligations', ['status', 'severity'], unique=False)
    op.create_table('risks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('risk_type', sa.Enum('missing_required_document', 'expired_certificate_or_insurance', 'inspection_failed_reinspection_required', 'approval_overdue', 'payment_term_conflict', 'scope_change_indicator', 'schedule_dependency_blocker', 'unknown_risk', name='risktype'), nullable=False),
    sa.Column('risk_text', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('needs_review', 'confirmed', 'rejected', name='reviewstatus'), server_default='needs_review', nullable=False),
    sa.Column('system_confidence', sa.Integer(), nullable=False),
    sa.Column('reviewer_confidence', sa.Integer(), nullable=True),
    sa.Column('has_external_reference', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('contradiction_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('reviewer_confidence IS NULL OR (reviewer_confidence >= 0 AND reviewer_confidence <= 100)', name='ck_risk_rev_conf'),
    sa.CheckConstraint('system_confidence >= 0 AND system_confidence <= 100', name='ck_risk_sys_conf'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risks_document_status', 'risks', ['document_id', 'status'], unique=False)
    op.create_table('obligation_contradictions',
    sa.Column('obligation_a_id', sa.UUID(), nullable=False),
    sa.Column('obligation_b_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('obligation_a_id < obligation_b_id', name='ck_obligation_pair_order'),
    sa.ForeignKeyConstraint(['obligation_a_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['obligation_b_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_a_id', 'obligation_b_id', name='uq_obligation_pair')
    )
    op.create_table('obligation_evidence',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_sha256', sa.String(), nullable=False),
    sa.Column('raw_char_start', sa.Integer(), nullable=False),
    sa.Column('raw_char_end', sa.Integer(), nullable=False),
    sa.Column('normalized_char_start', sa.Integer(), nullable=False),
    sa.Column('normalized_char_end', sa.Integer(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('pdf_text', 'ocr', name='textsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_sha256', 'document_id', 'page_number', 'normalized_char_start', 'normalized_char_end', name='uq_obligation_evidence_quote')
    )
    op.create_table('obligation_reviews',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', 'edit_approve', name='reviewdecision'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('field_edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer_confidence', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('reviewer_confidence IS NULL OR (reviewer_confidence >= 0 AND reviewer_confidence <= 100)', name='ck_obligation_review_conf'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_evidence',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_sha256', sa.String(), nullable=False),
    sa.Column('raw_char_start', sa.Integer(), nullable=False),
    sa.Column('raw_char_end', sa.Integer(), nullable=False),
    sa.Column('normalized_char_start', sa.Integer(), nullable=False),
    sa.Column('normalized_char_end', sa.Integer(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('pdf_text', 'ocr', name='textsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_sha256', 'document_id', 'page_number', 'normalized_char_start', 'normalized_char_end', name='uq_risk_evidence_quote')
    )
    op.create_table('risk_reviews',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', 'edit_approve', name='reviewdecision'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('field_edits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer_confidence', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('reviewer_confidence IS NULL OR (reviewer_confidence >= 0 AND reviewer_confidence <= 100)', name='ck_risk_review_conf'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_reviews')
    op.drop_table('risk_evidence')
    op.drop_table('obligation_reviews')
    op.drop_table('obligation_evidence')
    op.drop_table('obligation_contradictions')
    op.drop_index('ix_risks_document_status', table_name='risks')
    op.drop_table('risks')
    op.drop_index('ix_obligations_status_severity', table_name='obligations')
    op.drop_index('ix_obligations_due_date', table_name='obligations', postgresql_where=sa.text('due_date IS NOT NULL'))
    op.drop_index('ix_obligations_document_status', table_name='obligations')
    op.drop_table('obligations')
    op.drop_index('ix_text_spans_document_page', table_name='text_spans')
    op.drop_table('text_spans')
    op.drop_index('ix_extraction_runs_document_stage', table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_table('entity_mentions')
    op.drop_table('document_pages')
    op.drop_index('ix_chunks_document_page', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('user_asset_assignments')
    op.drop_table('documents')
    op.drop_index('ix_user_notifications_status', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_table('prompt_versions')
    op.drop_table('config_overrides')
    op.drop_index('ix_audit_table_record', table_name='audit_log')
    op.drop_index('ix_audit_performed_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('notification_events')
    op.drop_table('entities')
    # ### end Alembic commands ###
